INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (1, 'Historical Fiction', 'Chinua Achebe', 'The novel chronicles the life of Okonkwo, the leader of an Igbo community, from the events leading up to his banishment from the community for accidentally killing a clansman, through the seven years of his exile, to his return, and it addresses a particular problem of emergent Africa—the intrusion in the 1890s of white missionaries and colonial government into tribal Igbo society. Traditionally structured, and peppered with Igbo proverbs, it describes the simultaneous disintegration of its protagonist Okonkwo and of his village. The novel was praised for its intelligent and realistic treatment of tribal beliefs and of psychological disintegration coincident with social unraveling.','Teen');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (2, 'Fiction', 'Upton Sinclair', 'The Jungle is the story of Jurgis Rudkus and his family, Lithuanian immigrants who come to America to work in the meatpacking plants of Chicago. Their story is a story of hardship. They face enormous difficulties: harsh and dangerous working conditions, poverty and starvation, unjust businessmen who take their money, and corrupt politicians who create laws that allow all of this to happen. The story follows the hardships of Jurgis and his family and the transformation that Jurgis undergoes when he accepts the new political and economic revolution of socialism.','Teen');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (3, 'Southern Gothic Fiction', 'Harper Lee', 'To Kill a Mockingbird is set in the fictional town of Maycomb, Alabama, during the Great Depression (1929–39). The story centres on Jean Louise (“Scout”) Finch, an unusually intelligent girl who ages from six to nine years old during the novel. She and her brother, Jeremy Atticus (“Jem”), are raised by their widowed father, Atticus Finch. Atticus is a well-known and respected lawyer. He teaches his children to be empathetic and just, always leading by example. When Tom Robinson, one of the town’s Black residents, is falsely accused of raping Mayella Ewell, a young white woman, Atticus agrees to defend him despite threats from the community. Although Atticus presents a defense that gives a more plausible interpretation of the evidence—that Mayella was attacked by her father, Bob Ewell—Tom is convicted. He is later killed while trying to escape custody. The children, meanwhile, play out their own miniaturized drama. Scout and Jem become especially interested in the town recluse, Arthur (“Boo”) Radley, who interacts with them by leaving them small gifts in a tree. On Halloween, when Bob Ewell tries to attack Scout and Jem, Boo intervenes and saves them. Boo ultimately kills Ewell. The sheriff, however, decides to tell the community that Ewell’s death was an accident.
','Teen');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (4, 'Animal Fable', 'George Orwell', 'It tells the story of a group of farm animals who rebel against their human farmer, hoping to create a society where the animals can be equal, free, and happy. Ultimately, the rebellion is betrayed, and the farm ends up in a state as bad as it was before, under the dictatorship of a pig named Napoleon.','Teen');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (5, 'Historical Fiction', 'Anthony Doerr', ' All the Light We Cannot See is an up close and personal story of two kids, one a German orphan boy with incredible engineering skills, the other a blind French girl who loves to read and sometimes leaves the safety of her uncle’s home where she is cooped up, trying to keep out of the reach of Nazis during world war two. It is historical fiction about courage and hope. In a world tainted by war, death and loss, childhoods are broken. Kids are snatched out of their homes, the place that brought them comfort. Their dreams are shattered. The connections they had are lost. And they have to be strong, but not only for themselves, no, but also for their dear ones.','Teen');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (6, 'Fantasy', 'J.K. Rowling', 'On his 11th birthday, Harry receives a letter inviting him to study magic at the Hogwarts School of Witchcraft and Wizardry. Harry discovers that not only is he a wizard, but he is a famous one. He meets two best friends, Ron Weasley and Hermione Granger, and makes his first enemy, Draco Malfoy.','Children');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (7, 'Fantasy', 'J.K. Rowling', 'The plot follows Harry''s second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school''s corridors warn that the "Chamber of Secrets" has been opened and that the "heir of Slytherin" would kill all pupils who do not come from all-magical families.','Children');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (8, 'Fantasy', 'J.K. Rowling', 'The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ronald Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban, the wizard prison, believed to be one of Lord Voldemort''s old allies.','Children');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (9, 'Fantasy', 'J.K. Rowling', 'Harry must now survive through dragons, sea creatures and a terrifying maze, all before coming face-to-face with a particular dark wizard. The Tri-Wizard Tournament is open. Four champions are selected to compete in three terrifying tasks in order to win the Tri-Wizard Cup.','Children');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (10, 'Fantasy', 'J.K. Rowling', 'It follows Harry Potter''s struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L. exams, and an obstructive Ministry of Magic.','Children');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (11, 'Fantasy', 'J.K. Rowling', 'In this book, Harry Potter learns a lot about Lord Voldemort''s past, and Harry Potter prepares for the final battle against his nemesis with the help of Headmaster Dumbledore. But in that time, Voldemort returns to power, and makes a plan to destroy Harry.','Children');
INSERT INTO book (barcode, genre, author, summary, agerange)
	VALUES (12, 'Fantasy', 'J.K. Rowling', 'Harry, Ron, and Hermione assemble the books and tools necessary to embark on the quest that Dumbledore left them: to find and destroy the Horcruxes into which Voldemort placed fragments of his soul, making himself immortal as long as the objects survive.','Children');