INSERT INTO digital (barcode, genre, creator, digitaltype, description)
	VALUES (13, 'Action', 'Ryan Coogler', 'Movie', 'Queen Ramonda, Shuri, M''Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T''Challa''s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with Nakia and Everett Ross to forge a new path for their beloved kingdom.');
INSERT INTO digital (barcode, genre, creator, digitaltype, description)
	VALUES (14, 'Comedy', 'David Berenbaum', 'Movie', 'Buddy (Will Ferrell) was accidentally transported to the North Pole as a toddler and raised to adulthood among Santa''s elves. Unable to shake the feeling that he doesn''t fit in, the adult Buddy travels to New York, in full elf uniform, in search of his real father. As it happens, this is Walter Hobbs (James Caan), a cynical businessman. After a DNA test proves this, Walter reluctantly attempts to start a relationship with the childlike Buddy with increasingly chaotic results.');
INSERT INTO digital (barcode, genre, creator, digitaltype, description)
	VALUES (15, 'K-pop', 'BTS', 'Music', 'Proof maps the outline of BTS’s career across three collections: the first includes past title tracks and a new single, “Yet to Come (The Most Beautiful Moment),” the second is made up of pre-released sub unit and solo tracks hand-picked by the members as well as solid new offering “Run BTS,” and the third contains demos of both released and unreleased songs as well as the new ode to fans “For Youth.”');
INSERT INTO digital (barcode, genre, creator, digitaltype, description)
	VALUES (16, 'Rock', 'The Beatles', 'Music', 'Abbey Road is the eleventh studio album released by the English rock band the Beatles. It is the last album the group started recording,[1] although Let It Be was the last album completed before the band''s break-up in April 1970.');
INSERT INTO digital (barcode, genre, creator, digitaltype, description)
	VALUES (17, 'First-person shooter', 'Infinity Ward', 'Video Game', 'Call of Duty is a first-person shooter video game based on id Tech 3, and was released on October 29, 2003. The game was developed by Infinity Ward and published by Activision. The game simulates the infantry and combined arms warfare of World War II.');